/*
 * generated by Xtext
 */
package org.testeditor.xmllibrary.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AllActionGroupsDslRuntimeModule extends org.testeditor.xmllibrary.dsl.AbstractAllActionGroupsDslRuntimeModule {

}
