/*
 * generated by Xtext
 */
package org.testeditor.xmllibrary.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AllActionGroupsDslStandaloneSetup extends AllActionGroupsDslStandaloneSetupGenerated{

	public static void doSetup() {
		new AllActionGroupsDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

