/*
 * generated by Xtext
 */
package org.testeditor.xmllibrary.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AllActionGroupsDslUiModule extends org.testeditor.xmllibrary.dsl.ui.AbstractAllActionGroupsDslUiModule {
	public AllActionGroupsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
