sudo: required # run on old container infrastructure for more memory
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Configure Maven.
  - rm ~/.m2/settings.xml
  - export TE_MAVEN_HOME="$(dirname $(which mvn))/.."
  - export MAVEN_OPTS="-Xms256m -Xmx512m"
stages:
  - name: compileFeature
jobs:
  include:
    - stage: compileFeature
      script:
      - mvn clean install -f "target-platform/pom.xml"
      - mvn clean install -Dsurefire.useFile=false -Dtycho.localArtifacts=ignore
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis-publishOnRelease.sh # publishes only if tagged with v.*
