sudo: required # run on old container infrastructure for more memory
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Configure Maven.
  - rm ~/.m2/settings.xml
  - export TE_MAVEN_HOME="$(dirname $(which mvn))/.."
  - export MAVEN_OPTS="-Xms256m -Xmx512m"
stages:
  - name: compileFeature
    # just the language is built (te-web needs no more)
    if: (NOT (branch IN (master, develop) OR tag =~ ^v.*$ OR type IN (pull_request)))
  - name: compileRcp
    # complete build (including eclipse plugins, rcp and product)
    if: branch IN (master, develop) OR tag =~ ^v.*$ OR type IN (pull_request)
jobs:
  include:
    - stage: compileFeature
      script:
      - mvn clean install -f "target-platform/pom.xml"
      - mvn clean install -Dsurefire.useFile=false -Dtycho.localArtifacts=ignore
    - stage: compileRcp
      script:
      - mvn clean install -f "target-platform/pom.xml"
      - mvn clean install -Dmaven.test.failure.ignore -Dsurefire.useFile=false -Dtycho.localArtifacts=ignore -Prcp,product
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis-publishOnRelease.sh # publishes only if tagged with v.*
