language: java
sudo: false
jdk:
  - oraclejdk7
cache:
  directories:
  - $HOME/.m2
script:
  - clean install -f "releng/org.testeditor.autmaplib.releng.target/pom.xml"
  - clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - test -B