language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Configure Maven.
  - rm ~/.m2/settings.xml
  - export TE_MAVEN_HOME=/usr/local
  - export MAVEN_OPTS="-Xms512m -Xmx768m"
install:
  - mvn clean install -f "target-platform/pom.xml"
script:
  - mvn clean install -Dmaven.test.failure.ignore -Dsurefire.useFile=false -Dtycho.localArtifacts=ignore
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis-publishOnRelease.sh
