/*
 * generated by Xtext
 */
package org.testeditor.aml.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AmlUiModule extends org.testeditor.aml.dsl.ui.AbstractAmlUiModule {
	public AmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
