/*
 * generated by Xtext 2.9.0
 */
package org.testeditor.tsl.dsl.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;
import org.testeditor.tsl.dsl.ide.contentassist.antlr.TslParser;
import org.testeditor.tsl.dsl.ide.contentassist.antlr.internal.InternalTslLexer;

/**
 * Manual modifications go to {@link TslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractTslWebModule extends DefaultWebModule {

	public AbstractTslWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalTslLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return TslParser.class;
	}
	
}
