/*
 * generated by Xtext
 */
package org.testeditor.xmllibrary.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TechnicalBindingDslUiModule extends org.testeditor.xmllibrary.dsl.ui.AbstractTechnicalBindingDslUiModule {
	public TechnicalBindingDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
