/*
 * generated by Xtext
 */
package org.testeditor.tsl.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TestSpecDslStandaloneSetup extends TestSpecDslStandaloneSetupGenerated{

	public static void doSetup() {
		new TestSpecDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

