grammar org.testeditor.tsl.dsl.Tsl with org.eclipse.xtext.common.Terminals

generate tsl "http://www.testeditor.org/tsl/dsl/Tsl"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

TslModel:
	'package' package=QualifiedName
	steps+=SpecificationStep*;

QualifiedName:
	ID (=> '.' ID)*;

SpecificationStep:
	{SpecificationStep}
	'*' contents+=StepContent* '.'?;

StepContent:
	StepContentText | StepContentVariable;

StepContentText:
	value=ID;

StepContentVariable:
	value=STRING;