/*
 * generated by Xtext 2.9.0
 */
package org.testeditor.tsl.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TslStandaloneSetup extends TslStandaloneSetupGenerated {

	def static void doSetup() {
		new TslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
