/*
 * generated by Xtext
 */
package org.testeditor.aml.dsl.ui.contentassist

import org.testeditor.aml.dsl.ui.contentassist.AbstractAmlProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AmlProposalProvider extends AbstractAmlProposalProvider {
}
