/*
 * generated by Xtext
 */
/*
 * generated by Xtext
 */
package org.testeditor.xmllibrary.dsl.serializer;


class AllActionGroupsDslSyntacticSequencer extends AbstractAllActionGroupsDslSyntacticSequencer {
}
