/*
 * generated by Xtext
 */
package org.testeditor.tsl.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestSpecDslUiModule extends org.testeditor.tsl.dsl.ui.AbstractTestSpecDslUiModule {
	public TestSpecDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
