/*
 * generated by Xtext
 */
package org.testeditor.tsl.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TslUiModule extends org.testeditor.tsl.dsl.ui.AbstractTslUiModule {
	public TslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
