/*
 * generated by Xtext 2.9.0
 */
package org.testeditor.tsl.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TslUiModule extends AbstractTslUiModule {
}
