/*
 * generated by Xtext
 */
package org.testeditor.xmllibrary.dsl.ui.contentassist

import org.testeditor.xmllibrary.dsl.ui.contentassist.AbstractTechnicalBindingDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TechnicalBindingDslProposalProvider extends AbstractTechnicalBindingDslProposalProvider {
}
