/*
 * generated by Xtext
 */
package org.testeditor.aml.dsl.formatting2;

import org.eclipse.xtext.xbase.formatting2.XbaseFormatter

class AmlFormatter extends XbaseFormatter {
	
	// @Inject extension AmlGrammarAccess
	
}
