/*
 * generated by Xtext
 */
package org.testeditor.tsl.dsl.ui.contentassist

import org.testeditor.tsl.dsl.ui.contentassist.AbstractTslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TslProposalProvider extends AbstractTslProposalProvider {
}
