/*
 * generated by Xtext 2.9.0
 */
package org.testeditor.tsl.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.testeditor.tsl.TslModel

@RunWith(XtextRunner)
@InjectWith(TslInjectorProvider)
class TslParsingTest{

	@Inject
	ParseHelper<TslModel> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
