/*
 * generated by Xtext
 */
package org.testeditor.xmllibrary.dsl;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.testeditor.xmllibrary.dsl.naming.TechnicalBindingNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TechnicalBindingDslRuntimeModule extends org.testeditor.xmllibrary.dsl.AbstractTechnicalBindingDslRuntimeModule {

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return TechnicalBindingNameProvider.class;
	}
	
}
